### ISSUE TITLE
"kubectl tree" not working for Kubeflow profiles (not namespaced)

### ISSUE THREAD

**Issue by iptizer** [ahmetb/kubectl-tree#43]
Maybe I am doing something horrrably wrong here (please correct me if so), or there seems to be a problem for getting the graph from a Kubeflow profiles CRD.

```sh
❯ kubectl tree profiles my-kubeflow-user
No resources are owned by this object through ownerReferences.
```

This resoruce look slike as follows (removed not necessary parts):

```yml
❯ kubectl get profiles my-kubeflow-user -o yaml
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: my-kubeflow-user
spec:
  owner:
    kind: User
    name: myuser@domain.com
```

This resource then creates e.g. a namespace:

```yml
❯ kubectl get ns my-kubeflow-user -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    owner: myuser@domain.com
  labels:
    app.kubernetes.io/part-of: kubeflow-profile
    istio-injection: enabled
  name: my-kubeflow-user
  ownerReferences:
  - apiVersion: kubeflow.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: Profile
    name: my-kubeflow-user
    uid: c39a1fbe-7805-4696-85a6-1234f902cc2b
status:
  phase: Active
```

Maybe it is because it is a CRD, or because it is not namespaced?
