### ISSUE TITLE
Doesn't take into account cluster.proxy-url

### ISSUE THREAD

**Issue by gabrielbcn** [ahmetb/kubectl-tree#50]
When I use clusters described with a proxy-url in kubeconfig:

```
- cluster:
    certificate-authority-data: DATA+OMITTED
    proxy-url: http://localhost:9000
    server: ...
```

I end up getting a timeout to another IP:

`Error: failed to get deploy/echoserver: Get "https://XXX/apis/apps/v1/namespaces/default/deployments/echoserver": dial tcp 104.43.X.X:443: i/o timeout`

Would it be possible to have this field honoured? Or a workaround?

Thanks
